### ISSUE TITLE
error

### ISSUE THREAD

**Issue by UTrosh** [its0x08/duckduckgo#2]
ModuleNotFoundError: No module named 'urllib2'

**Comment by its0x08** [comment]
Replace it with urllib3 or python 2.7

Feel free to create a pull request with your fix 😁❗

**Comment by UTrosh** [comment]
Okep, another thing, the iptv brute working?

**Comment by its0x08** [comment]
Also outdated!

**Comment by UTrosh** [comment]
ah, sad
